# Generated by Django 5.0.4 on 2024-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Product name", max_length=155)),
                ("qty", models.IntegerField()),
                ("price", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
    ]
