# Generated by Django 5.0.4 on 2024-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="User Name", max_length=155)),
                ("password", models.CharField(default="11111", max_length=155)),
                ("email", models.EmailField(max_length=122)),
                ("phone", models.CharField(default="User Phone", max_length=122)),
                ("position", models.CharField(default="Admin", max_length=54)),
            ],
        ),
    ]
