# Generated by Django 5.0.4 on 2024-10-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="User Name", max_length=155)),
                ("password", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=122)),
                ("phone", models.CharField(default="User Phone", max_length=122)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("manager", "Manager"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
