# Generated by Django 5.0.4 on 2024-10-26 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_baseuser_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BaseUser",
            new_name="User",
        ),
    ]
