# Generated by Django 5.0.4 on 2024-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_is_active_user_is_staff_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=122),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=155),
        ),
    ]
